"Priority: Low":
  - "### Priority level\n\nLow"
"Priority: Medium":
  - "### Priority level\n\nMedium"
"Priority: High 🔥":
  - "### Priority level\n\nHigh"
"Priority: CRITICAL 🌋":
  - "### Priority level\n\nCritical"